# Generated by Django 5.2.5 on 2025-08-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentcategory',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True, verbose_name='Is Active'),
        ),
    ]
