# Generated by Django 5.2.5 on 2025-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0002_incidentcategory_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentState',
            fields=[
                ('id_state', models.AutoField(db_column='id_state', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Incident State',
                'verbose_name_plural': 'Incident States',
                'db_table': 'incident_state',
            },
        ),
    ]
