# Generated by Django 5.2.5 on 2025-08-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0003_incidentstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photography',
            name='url',
        ),
        migrations.AddField(
            model_name='photography',
            name='content_type',
            field=models.CharField(blank=True, db_column='content_type', default='', max_length=200, verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='photography',
            name='file_size',
            field=models.BigIntegerField(blank=True, default=0, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='photography',
            name='name',
            field=models.CharField(db_column='name', default='photo', max_length=200, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='photography',
            name='r2_key',
            field=models.CharField(blank=True, help_text='Unique key in R2 bucket', max_length=500, null=True),
        ),
    ]
