# Generated by Django 5.2.5 on 2025-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maps', '0004_remove_photography_url_photography_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentstate',
            name='color',
            field=models.CharField(db_column='color', default='#000000', max_length=200, verbose_name='Color'),
        ),
    ]
